[package]
name = "eds-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-eds = "^0.0.1"
tree-sitter = "^0.20"
tower-lsp = "^0.20"
tokio = {version = "^1.32", features = ["full"]}
